// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5CApJ-yCYL0in4-9sdfhl-WYcM37BbAQ',
    appId: '1:581348652431:web:48d0647458923559e007fa',
    messagingSenderId: '581348652431',
    projectId: 'ai-app-8901c',
    authDomain: 'ai-app-8901c.firebaseapp.com',
    storageBucket: 'ai-app-8901c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqX3rApXdXWnKBYq64xoPBy_SyZmcGbx4',
    appId: '1:581348652431:android:23172e1dbdafc771e007fa',
    messagingSenderId: '581348652431',
    projectId: 'ai-app-8901c',
    storageBucket: 'ai-app-8901c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMQdxOOpKkZAh0n0YJDr1Fzq606ARsFw4',
    appId: '1:581348652431:ios:5f617c48b34efe73e007fa',
    messagingSenderId: '581348652431',
    projectId: 'ai-app-8901c',
    storageBucket: 'ai-app-8901c.firebasestorage.app',
    iosBundleId: 'com.example.aiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMQdxOOpKkZAh0n0YJDr1Fzq606ARsFw4',
    appId: '1:581348652431:ios:5f617c48b34efe73e007fa',
    messagingSenderId: '581348652431',
    projectId: 'ai-app-8901c',
    storageBucket: 'ai-app-8901c.firebasestorage.app',
    iosBundleId: 'com.example.aiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5CApJ-yCYL0in4-9sdfhl-WYcM37BbAQ',
    appId: '1:581348652431:web:8abdc33dd55917dfe007fa',
    messagingSenderId: '581348652431',
    projectId: 'ai-app-8901c',
    authDomain: 'ai-app-8901c.firebaseapp.com',
    storageBucket: 'ai-app-8901c.firebasestorage.app',
  );
}
